"""Тест Computed

Revision ID: 0fbaf6945b4b
Revises: 1c1ae8a7bc98
Create Date: 2025-02-16 01:10:04.167725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbaf6945b4b'
down_revision: Union[str, None] = '1c1ae8a7bc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
